"""Process → research universe (tables + display t-codes).

Catalog names are examples. Unknown processes still get a large walkable set.
This is not a 10-table demo list. Live F7 still takes seconds each — the runner
prioritises the spine, then adjacent hops, then config.
"""
from __future__ import annotations

from sapilot.display.policy import assert_display_tcode, DisplayPolicyError
from sapilot.product.analyze import analyze_process, _resolve

# Process-first tables. Zero on the glass is a finding, not a skip.
_PROCESS_TABLES: dict[str, list[str]] = {
    "rar": [
        "FARR_D_CONTRACT",
        "FARR_D_POB",
        "FARR_D_DEFITEM",
        "FARR_D_REVENUE",
        "FARR_D_FULFILL",
        "FARR_D_INV_ITM",
        "FARR_D_BILLING",
        "FARR_D_MAPPING",
        "FARR_D_PERIOD",
        "FARR_D_POSTING",
        "FARR_D_CONTR_H",
        "FARR_D_CONTR_I",
        "FARR_D_POB_CHG",
        "FARR_D_DEFERRAL",
        "FARR_RAI_HD",
        "FARR_RAI_IT",
        "FARR_C_PROCESS",
        "FARR_C_ACCASS",
        "FARR_C_EXPL",
        "FARR_C_CONS",
        "VBREVK",
        "VBREVE",
        "VBREVR",
        "VBAK",
        "VBAP",
        "VBKD",
        "VBPA",
        "VBFA",
        "VBRK",
        "VBRP",
        "LIKP",
        "LIPS",
        "BSID",
        "BSAD",
        "BKPF",
        "BSEG",
        "NAST",
        "PRCD_ELEMENTS",
        "KONV",
        "ACDOCA",
        "TVAK",
        "TVFK",
        "TVCPF",
        "KNKK",
        "KNVV",
        "KNA1",
    ],
    "otc": [
        "VBAK",
        "VBAP",
        "VBEP",
        "VBKD",
        "VBPA",
        "VBFA",
        "LIKP",
        "LIPS",
        "VBRK",
        "VBRP",
        "BSID",
        "BSAD",
        "NAST",
        "EDIDC",
        "KNA1",
        "KNVV",
        "KNKK",
        "MVKE",
        "TVAK",
        "TVLK",
        "TVFK",
    ],
    "ptp": [
        "EKKO",
        "EKPO",
        "EKBE",
        "EKET",
        "EBAN",
        "EKES",
        "EKKN",
        "MKPF",
        "MSEG",
        "RBKP",
        "RSEG",
        "BSIK",
        "BSAK",
        "LFA1",
        "LFB1",
        "EINA",
        "EINE",
        "MARA",
        "MARC",
        "T161",
        "T163",
    ],
    "copc": [
        "KEKO",
        "KEPH",
        "CKIS",
        "CKHS",
        "TCK03",
        "TCK31",
        "TCK05",
        "TCK14",
        "TCKH1",
        "CKMLHD",
        "CKMLCR",
        "CKMLPP",
        "CKMLPR",
        "AUFK",
        "AFKO",
        "AFPO",
        "AFRU",
        "MBEW",
        "QBEW",
        "EBEW",
        "CSKB",
        "CSKS",
        "TKA01",
        "TKA02",
    ],
    "collections": [
        "BSID",
        "BSAD",
        "KNA1",
        "KNB1",
        "KNVV",
        "KNKK",
        "MHNK",
        "MHND",
        "NAST",
        "VBRK",
        "BKPF",
        "FDM_DCOBJ",
        "UDM_COLL_ITEM",
    ],
    "treasury": [
        "T001",
        "T012",
        "T012K",
        "T012T",
        "BNKA",
        "VTBFHA",
        "VTBFHAPO",
        "VTBFINKO",
        "TRLT_TRANSACTION",
        "TRLT_FLOW",
        "FDES",
        "FDFI",
        "SKB1",
        "BSEG",
    ],
    "quality": [
        "QMAT",
        "QALS",
        "QAMR",
        "QAVE",
        "QAMB",
        "QAPP",
        "MARA",
        "MARC",
        "MSEG",
    ],
    "warehouse": [
        "T300",
        "T301",
        "T320",
        "LAGP",
        "LQUA",
        "LTAP",
        "LTK",
        "LIKP",
        "LIPS",
        "VEKP",
        "VEPO",
    ],
    "maintenance": [
        "EQUI",
        "EQKT",
        "IFLOT",
        "QMEL",
        "QMFE",
        "AUFK",
        "AFKO",
        "AFRU",
        "IHPA",
    ],
    "project": [
        "PROJ",
        "PRPS",
        "PRHI",
        "AUFK",
        "AFVC",
        "COEP",
        "RPSCO",
        "MSPR",
    ],
    "production": [
        "AUFK",
        "AFKO",
        "AFPO",
        "AFVC",
        "RESB",
        "AFRU",
        "MARA",
        "MAST",
        "STKO",
        "STPO",
        "PLKO",
        "PLPO",
        "CKMLHD",
    ],
    "credit": [
        "KNKK",
        "KNKA",
        "UKMBP_CMS",
        "UKM_ITEM",
        "VBAK",
        "VBUK",
        "KNA1",
        "BSID",
    ],
    "tax": [
        "T007A",
        "T007B",
        "T007S",
        "BSET",
        "VBRK",
        "BSEG",
        "EDOC_SOURCE",
        "EDOCUMENT",
        "KNA1",
    ],
    "hr": [
        "PA0000",
        "PA0001",
        "PA0002",
        "PA0008",
        "T500P",
        "T001P",
        "PCL2",
        "HRP1000",
        "HRP1001",
    ],
    "intercompany": [
        "EKKO",
        "EKPO",
        "VBAK",
        "VBRK",
        "LIKP",
        "MKPF",
        "MSEG",
        "BKPF",
        "T001W",
        "T001K",
    ],
    "r2r": [
        "BKPF",
        "BSEG",
        "BSIS",
        "BSAS",
        "SKA1",
        "SKB1",
        "FAGLFLEXA",
        "ACDOCA",
        "T001",
        "TKA01",
        "COEP",
        "COSP",
    ],
}

_ORG = [
    "T000",
    "T001",
    "T001K",
    "T001W",
    "T001L",
    "T005",
    "T005S",
    "TCURC",
    "TCURR",
    "TCURT",
    "T024",
    "T024E",
    "T161",
    "T161T",
    "T163",
    "TVKO",
    "TVKOT",
    "TVTW",
    "TVKOV",
    "TVBUR",
    "TVKGR",
    "TVTA",
    "TVAK",
    "TVAKT",
    "TVAP",
    "TVLK",
    "TVLKT",
    "TVLP",
    "TVFK",
    "TVFKT",
    "TVFP",
    "TVCPF",
    "TKA01",
    "TKA02",
    "TKA03",
    "CSKS",
    "CSKT",
    "T003",
    "T003T",
    "T007A",
    "T007S",
    "T012",
    "T012K",
    "T042",
    "T042Z",
]

_SD = [
    "VBAK",
    "VBAP",
    "VBEP",
    "VBKD",
    "VBPA",
    "VBFA",
    "VBBE",
    "VBUK",
    "VBUP",
    "VBLB",
    "VBRP",
    "VBRK",
    "VRKPA",
    "LIKP",
    "LIPS",
    "LIPSO2",
    "VBRL",
    "VTTP",
    "VTTK",
    "VTTS",
    "VTFA",
    "VEKP",
    "VEPO",
    "VBUV",
    "VBFS",
    "VBSK",
    "VBSS",
    "VBKFZ",
    "VBMUE",
    "KONV",
    "KONH",
    "KONP",
    "KONM",
    "KONW",
    "PRCD_ELEMENTS",
    "PRCD_HEAD",
    "NAST",
    "NACH",
    "TNAPR",
    "TNATI",
    "EDIDC",
    "EDIDS",
    "EDID4",
    "EDP13",
    "TVAK",
    "TVAP",
    "TVAGT",
    "T176",
    "TVAG",
    "KNA1",
    "KNB1",
    "KNBK",
    "KNVV",
    "KNVP",
    "KNVI",
    "KNKK",
    "KNKA",
    "KNVK",
    "KNVS",
    "ADR6",
    "ADRC",
    "MVKE",
    "MARA",
    "MAKT",
    "MARC",
    "MARD",
    "MBEW",
    "MLAN",
    "MEAN",
    "MARM",
]

_MM = [
    "EKKO",
    "EKPO",
    "EKET",
    "EKBE",
    "EKES",
    "EKKN",
    "EKKN",
    "EKPA",
    "EORD",
    "EBAN",
    "EBKN",
    "EINA",
    "EINE",
    "EIPA",
    "MKPF",
    "MSEG",
    "MCHB",
    "MCH1",
    "MSKA",
    "MSKU",
    "MSSA",
    "MSSL",
    "RBKP",
    "RSEG",
    "RBCO",
    "LFA1",
    "LFB1",
    "LFBK",
    "LFM1",
    "T161",
    "T163",
    "T024",
    "T024E",
    "T16FS",
    "T16FB",
    "T001W",
    "T001L",
    "MARA",
    "MARC",
    "MARD",
    "MBEW",
    "EBEW",
    "QBEW",
]

_FI = [
    "BKPF",
    "BSEG",
    "BSET",
    "BSEC",
    "BSID",
    "BSAD",
    "BSIK",
    "BSAK",
    "BSIS",
    "BSAS",
    "FAGLFLEXA",
    "FAGLFLEXT",
    "ACDOCA",
    "SKA1",
    "SKAT",
    "SKB1",
    "SKA1",
    "T001",
    "T003",
    "T007A",
    "T030",
    "T030K",
    "T030B",
    "T074",
    "KNB1",
    "LFB1",
    "REGUH",
    "REGUP",
    "PAYR",
    "T042",
    "T042B",
    "T042Z",
    "T042E",
    "T042I",
    "T012",
    "T012K",
]

_CO = [
    "COEP",
    "COSP",
    "COSS",
    "COBK",
    "COEJ",
    "COKA",
    "CSKS",
    "CSKT",
    "CSKB",
    "CSKU",
    "TKA01",
    "TKA02",
    "TKA03",
    "TKA09",
    "CEPC",
    "CEPCT",
    "AUFK",
    "AFKO",
    "AFPO",
    "AFRU",
    "AFVC",
    "RESB",
    "KEKO",
    "KEPH",
    "CKIS",
    "CKHS",
    "CKIT",
    "TCK03",
    "TCK05",
    "TCK09",
    "TCK14",
    "TCK31",
    "TCKH1",
    "TCKH2",
    "TCKH3",
    "CKMLHD",
    "CKMLCR",
    "CKMLPP",
    "CKMLPR",
    "CKMLMV001",
    "CKMLMV003",
    "MLCD",
    "MLHD",
    "MLIT",
    "MLPP",
    "TKKAA",
    "TKKAP",
]

_PP_QM_PM_PS_WM = [
    "MAST",
    "STKO",
    "STPO",
    "STAS",
    "STZU",
    "PLKO",
    "PLPO",
    "PLAS",
    "MAPL",
    "CRHD",
    "CRTX",
    "KAKO",
    "QMAT",
    "QALS",
    "QAMR",
    "QASR",
    "QAVE",
    "QAMB",
    "QAPP",
    "QAMV",
    "EQUI",
    "EQKT",
    "EQUZ",
    "ILOA",
    "IFLOT",
    "IFLOTX",
    "QMEL",
    "QMFE",
    "QMUR",
    "IHPA",
    "PROJ",
    "PRPS",
    "PRHI",
    "PRTE",
    "RPSCO",
    "T300",
    "T301",
    "T302",
    "T320",
    "T321",
    "T330",
    "LAGP",
    "LQUA",
    "LTAK",
    "LTAP",
    "LINV",
    "MLGT",
    "MLGN",
]

_TR_HR_BASIS = [
    "VTBFHA",
    "VTBFHAPO",
    "VTBFINKO",
    "VTB_ASGN",
    "TRLT_TRANSACTION",
    "TRLT_FLOW",
    "FDES",
    "PA0000",
    "PA0001",
    "PA0002",
    "PA0006",
    "PA0008",
    "PA0009",
    "PA0014",
    "PA0015",
    "HRP1000",
    "HRP1001",
    "T500P",
    "T001P",
    "T527X",
    "USR02",
    "USR04",
    "AGR_USERS",
    "AGR_1251",
    "AGR_TCODES",
    "TSTCT",
    "TSTC",
    "DD02L",
    "DD02T",
    "DD03L",
    "CDHDR",
    "CDPOS",
    "NRIV",
    "TNRO",
    "STXH",
    "STXL",
    "SOST",
    "NAST",
    "NACH",
]

_RAR_MORE = [
    "FARR_D_CONTRACT",
    "FARR_D_POB",
    "FARR_D_DEFITEM",
    "FARR_D_REVENUE",
    "FARR_D_FULFILL",
    "FARR_D_INV_ITM",
    "FARR_D_BILLING",
    "FARR_D_MAPPING",
    "FARR_D_PERIOD",
    "FARR_D_POSTING",
    "FARR_D_CONTR_H",
    "FARR_D_CONTR_I",
    "FARR_D_POB_CHG",
    "FARR_D_DEFERRAL",
    "FARR_D_TRACE",
    "FARR_D_HIST",
    "FARR_D_COND",
    "FARR_D_PRICE",
    "FARR_D_EVENT",
    "FARR_D_SSP",
    "FARR_RAI_HD",
    "FARR_RAI_IT",
    "FARR_RAI_AD",
    "FARR_C_PROCESS",
    "FARR_C_ACCASS",
    "FARR_C_EXPL",
    "FARR_C_CONS",
    "FARR_C_TYPE",
    "FARR_C_POBTYP",
    "FARR_C_EVENT",
    "FARR_C_SSPMETH",
    "VBREVK",
    "VBREVE",
    "VBREVR",
    "VBREVC",
]

_CORE = _ORG + _SD + _MM + _FI + _CO + _PP_QM_PM_PS_WM + _TR_HR_BASIS + _RAR_MORE


def _uniq(seq: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for raw in seq:
        t = (raw or "").strip().upper()
        if not t or t in seen:
            continue
        seen.add(t)
        out.append(t)
    return out


def plan_tables(process_key: str | None, asked: str) -> list[str]:
    """Spine tables first, then adjacent families, then the rest of the book."""
    first: list[str] = []
    if process_key and process_key in _PROCESS_TABLES:
        first.extend(_PROCESS_TABLES[process_key])
    # keyword extras when the user named something not in the alias map
    low = (asked or "").lower()
    for key, tabs in _PROCESS_TABLES.items():
        if key in low or any(p in low for p in key.split()):
            first.extend(tabs)
    return _uniq(first + _CORE)


def plan_tcodes(process_key: str | None, asked: str) -> list[dict]:
    rec = analyze_process(asked or process_key or "process")
    out: list[dict] = []
    seen: set[str] = set()
    for s in rec.get("steps") or []:
        code = (s.get("tcode") or "").upper()
        if not code or code in seen:
            continue
        try:
            code = assert_display_tcode(code)
        except DisplayPolicyError:
            continue
        seen.add(code)
        out.append(
            {
                "tcode": code,
                "phase": s.get("phase") or "",
                "purpose": s.get("purpose") or "",
            }
        )
    extras = ["SE16N", "VA03", "VF03", "FB03", "MM03", "XD03", "ME23N"]
    for code in extras:
        if code in seen:
            continue
        try:
            code = assert_display_tcode(code)
        except DisplayPolicyError:
            continue
        seen.add(code)
        out.append({"tcode": code, "phase": "display", "purpose": "Display hop on the glass"})
    return out


def plan_research(asked: str, *, max_tables: int | None = None) -> dict:
    rec = analyze_process(asked)
    kind, key = _resolve(asked)
    tables = plan_tables(key if kind in {"library", "catalog"} else None, asked)
    if max_tables and max_tables > 0:
        tables = tables[: int(max_tables)]
    tcodes = plan_tcodes(key if kind in {"library", "catalog"} else None, asked)
    return {
        "ok": True,
        "asked": asked,
        "process_key": key,
        "kind": rec.get("source") or kind,
        "title": rec.get("title"),
        "spine": rec.get("spine"),
        "story": rec.get("story"),
        "hops": rec.get("hops") or [],
        "questions": rec.get("questions") or [],
        "scenarios": rec.get("scenarios") or [],
        "tables": tables,
        "tcodes": tcodes,
        "universe": len(tables),
    }
