"""Human-readable HTML report — the audit / demo deliverable."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Template

from sapilot.schemas import DiagnosisReport, EvidencePack

_TEMPLATE = Template(
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>SAPILOT Report {{ run_id }}</title>
<style>
  body { font-family: Segoe UI, system-ui, sans-serif; margin: 2rem; color: #1a1a1a; }
  h1 { border-bottom: 2px solid #0b5fff; padding-bottom: .3rem; }
  .meta { color: #555; margin-bottom: 1.5rem; }
  .ok { color: #0a7a2f; } .bad { color: #b00020; } .warn { color: #9a6700; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 0.92rem; }
  th, td { border: 1px solid #ddd; padding: 0.45rem 0.6rem; text-align: left; vertical-align: top; }
  th { background: #f4f6f8; }
  code { background: #f0f0f0; padding: 0.1rem 0.3rem; }
  .summary { background: #f8fafc; border-left: 4px solid #0b5fff; padding: 1rem; }
</style>
</head>
<body>
  <h1>SAPILOT Report</h1>
  <div class="meta">
    <div><strong>Run ID:</strong> {{ run_id }}</div>
    {% if evidence %}
    <div><strong>Goal:</strong> {{ evidence.goal }}</div>
    <div><strong>Tier:</strong> {{ evidence.tier.value }}</div>
    <div><strong>Outcome:</strong>
      <span class="{{ 'ok' if evidence.outcome.value == 'SUCCESS' else 'bad' }}">
        {{ evidence.outcome.value }}
      </span>
    </div>
    <div><strong>Elapsed:</strong> {{ '%.1f'|format(evidence.elapsed_seconds) }}s ·
         <strong>Remediation steps:</strong> {{ evidence.remediation_steps }}</div>
    {% if evidence.regup_count is not none %}
    <div><strong>REGUV:</strong> {{ evidence.reguv_status }} ·
         <strong>REGUP rows:</strong> {{ evidence.regup_count }}</div>
    {% endif %}
    {% endif %}
  </div>

  {% if diagnosis %}
  <h2>Diagnostic findings</h2>
  <div class="summary">{{ diagnosis.summary }}</div>
  <p>Company code <code>{{ diagnosis.company_code }}</code> ·
     Payment method <code>{{ diagnosis.payment_method }}</code> ·
     Vendors checked: {{ diagnosis.vendors_checked|length }}</p>
  <table>
    <thead>
      <tr>
        <th>Severity</th><th>Symptom</th><th>Table</th><th>Key</th>
        <th>Field</th><th>Current</th><th>Recommended</th><th>Remediation</th>
      </tr>
    </thead>
    <tbody>
    {% for f in diagnosis.findings %}
      <tr>
        <td class="{{ 'bad' if f.severity=='blocker' else 'warn' if f.severity=='warning' else '' }}">
          {{ f.severity }}
        </td>
        <td>{{ f.symptom }}</td>
        <td><code>{{ f.cause_table }}</code></td>
        <td><code>{{ f.cause_key }}</code></td>
        <td><code>{{ f.cause_field }}</code></td>
        <td>{{ f.current_value }}</td>
        <td>{{ f.recommended_value }}</td>
        <td>{{ f.remediation }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}

  {% if journal_tail %}
  <h2>Journal (tail)</h2>
  <table>
    <thead><tr><th>Time</th><th>Type</th><th>Payload</th></tr></thead>
    <tbody>
    {% for e in journal_tail %}
      <tr>
        <td>{{ e.ts }}</td>
        <td>{{ e.type }}</td>
        <td><code>{{ e.payload_preview }}</code></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}

  <p class="meta">Generated by SAPILOT · text-tree first · redaction applied on model egress</p>
</body>
</html>
"""
)


def render_html_report(
    path: Path,
    *,
    run_id: str,
    diagnosis: DiagnosisReport | None = None,
    evidence: EvidencePack | None = None,
    journal_events: list[dict[str, Any]] | None = None,
) -> Path:
    tail = []
    for e in (journal_events or [])[-50:]:
        payload = e.get("payload")
        preview = str(payload)[:300]
        tail.append({"ts": e.get("ts"), "type": e.get("type"), "payload_preview": preview})
    html = _TEMPLATE.render(
        run_id=run_id,
        diagnosis=diagnosis,
        evidence=evidence,
        journal_tail=tail,
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path
